const travelWords = [
  // COUNTRIES & DESTINATIONS (150+)
  'dubai', 'abuja', 'accra', 'addis', 'addis ababa', 'cairo', 'cape town', 'dakar', 'dar es salaam',
  'diani', 'durban', 'entebbe', 'harare', 'johannesburg', 'kampala', 'kigali', 'kilimanjaro',
  'kinshasa', 'lagos', 'lusaka', 'mauritius', 'malindi', 'mombasa', 'nairobi', 'naivasha',
  'nakuru', 'pretoria', 'seychelles', 'zanzibar', 'zimbabwe', 'qatar', 'doha', 'india', 'mumbai',
  'delhi', 'goa', 'kerala', 'chennai', 'bangalore', 'hyderabad', 'kolkata', 'jaipur', 'agra',
  'rajasthan', 'punjab', 'gujarat', 'thailand', 'bangkok', 'phuket', 'pattaya', 'chiang mai',
  'krabi', 'samui', 'uk', 'london', 'manchester', 'birmingham', 'liverpool', 'edinburgh',
  'glasgow', 'usa', 'new york', 'los angeles', 'chicago', 'houston', 'phoenix', 'philadelphia',
  'san antonio', 'san diego', 'dallas', 'austin', 'boston', 'atlanta', 'miami', 'seattle',
  'denver', 'orlando', 'detroit', 'portland', 'las vegas', 'nashville', 'turkey', 'istanbul',
  'ankara', 'izmir', 'antalya', 'bodrum', 'cappadocia', 'egypt', 'morocco', 'casablanca',
  'marrakech', 'rabat', 'fes', 'tangier', 'agadir', 'tanzania', 'uganda', 'rwanda', 'burundi',
  'ethiopia', 'eritrea', 'sudan', 'south sudan', 'somalia', 'djibouti', 'malawi', 'mozambique',
  'botswana', 'namibia', 'zambia', 'angola', 'congo', 'cameroon', 'ghana', 'nigeria', 'senegal',
  'ivory coast', 'mali', 'mauritania', 'algeria', 'tunisia', 'libya', 'jordan', 'lebanon',
  'kuwait', 'bahrain', 'oman', 'saudi', 'riyadh', 'jeddah', 'mecca', 'medina', 'sharm',
  'sharm el sheikh', 'hurghada', 'maldives', 'sri lanka', 'colombo', 'singapore', 'malaysia',
  'kuala lumpur', 'penang', 'langkawi', 'jakarta', 'bali', 'surabaya', 'manila', 'cebu',
  'boracay', 'beijing', 'shanghai', 'guangzhou', 'shenzhen', 'beijing', 'hong kong', 'macau',
  'taipei', 'tokyo', 'osaka', 'kyoto', 'yokohama', 'seoul', 'busan', 'vietnam', 'hanoi',
  'ho chi minh', 'da nang', 'nha trang', 'cambodia', 'phnom penh', 'siem reap', 'laos',
  'vientiane', 'luang prabang', 'myanmar', 'yangon', 'bagan', 'nepal', 'kathmandu', 'pokhara',
  'bhutan', 'thimphu', 'bangladesh', 'dhaka', 'pakistan', 'karachi', 'lahore', 'islamabad',
  'afghanistan', 'kabul', 'iran', 'tehran', 'iraq', 'baghdad', 'syria', 'damascus', 'yemen',
  'sanaa', 'palestine', 'ramallah', 'israel', 'tel aviv', 'jerusalem', 'cyprus', 'nicosia',
  'greece', 'athens', 'santorini', 'mykonos', 'crete', 'italy', 'rome', 'venice', 'milan',
  'florence', 'naples', 'spain', 'madrid', 'barcelona', 'valencia', 'seville', 'france',
  'paris', 'nice', 'lyon', 'marseille', 'germany', 'berlin', 'munich', 'frankfurt', 'hamburg',
  'netherlands', 'amsterdam', 'rotterdam', 'belgium', 'brussels', 'antwerp', 'austria',
  'vienna', 'salzburg', 'switzerland', 'zurich', 'geneva', 'berne', 'sweden', 'stockholm',
  'gothenburg', 'norway', 'oslo', 'bergen', 'denmark', 'copenhagen', 'finland', 'helsinki',
  'poland', 'warsaw', 'krakow', 'czech', 'prague', 'hungary', 'budapest', 'romania', 'bucharest',
  'bulgaria', 'sofia', 'serbia', 'belgrade', 'croatia', 'zagreb', 'dubrovnik', 'slovenia',
  'ljubljana', 'slovakia', 'bratislava', 'estonia', 'tallinn', 'latvia', 'riga', 'lithuania',
  'vilnius', 'russia', 'moscow', 'st petersburg', 'ukraine', 'kyiv', 'belarus', 'minsk',
  'australia', 'sydney', 'melbourne', 'brisbane', 'perth', 'adelaide', 'canberra', 'new zealand',
  'auckland', 'wellington', 'christchurch', 'fiji', 'suva', 'nadi', 'papua new guinea', 'port moresby',

  // VISA RELATED (80+)
  'visa', 'tourist visa', 'business visa', 'transit visa', 'work visa', 'student visa', 'e-visa',
  'visa on arrival', 'visa free', 'visa fee', 'visa cost', 'visa price', 'visa requirements',
  'visa process', 'visa application', 'visa status', 'visa approval', 'visa rejection',
  'visa extension', 'visa stamp', 'visa validity', 'visa duration', 'multiple entry',
  'single entry', 'visa type', 'visa category', 'visa policy', 'visa regulations', 'visa rules',
  'visa documents', 'visa photo', 'passport photo', 'bio page', 'passport copy', 'visa form',
  'application form', 'visa interview', 'visa appointment', 'visa processing time', 'processing time',
  'turnaround time', 'express visa', 'urgent visa', 'emergency visa', 'visa assistance',
  'visa help', 'visa support', 'visa service', 'visa agency', 'visa consultant', 'visa expert',
  'schengen visa', 'uk visa', 'us visa', 'canada visa', 'australia visa', 'new zealand visa',
  'dubai visa', 'uae visa', 'qatar visa', 'saudi visa', 'oman visa', 'kuwait visa', 'bahrain visa',
  'india visa', 'thailand visa', 'singapore visa', 'malaysia visa', 'china visa', 'japan visa',
  'south korea visa', 'turkey visa', 'egypt visa', 'morocco visa', 'south africa visa',
  'kenya visa', 'tanzania visa', 'uganda visa', 'rwanda visa', 'ethiopia visa', 'nigeria visa',
  'ghana visa', 'senegal visa', 'east africa visa', 'eac visa', 'tourist eVisa', 'business eVisa',

  // FLIGHT RELATED (100+)
  'flight', 'flights', 'air ticket', 'plane ticket', 'return ticket', 'round trip', 'one way',
  'two way', 'multi city', 'open jaw', 'direct flight', 'non stop', 'connecting flight',
  'layover', 'stopover', 'transit', 'flight booking', 'book flight', 'flight reservation',
  'flight price', 'flight cost', 'flight fare', 'cheap flight', 'best flight', 'flight deals',
  'flight offers', 'flight discount', 'flight promotion', 'flight time', 'departure time',
  'arrival time', 'take off', 'landing', 'airline', 'airlines', 'airline name', 'airline code',
  'economy class', 'economy', 'premium economy', 'business class', 'first class', 'business',
  'first', 'class upgrade', 'seat selection', 'seat number', 'window seat', 'aisle seat',
  'baggage', 'luggage', 'checked bag', 'carry on', 'hand luggage', 'baggage allowance',
  'extra baggage', 'overweight baggage', 'check in', 'online check in', 'mobile check in',
  'boarding pass', 'e boarding pass', 'gate', 'terminal', 'departure gate', 'arrival gate',
  'flight status', 'flight delay', 'flight cancellation', 'flight change', 'flight reschedule',
  'rebooking', 'refund', 'flight refund', 'cancellation policy', 'change fee', 'rebooking fee',
  'flight schedule', 'flight timetable', 'departure board', 'arrival board', 'airport code',
  'airport transfer', 'airport pickup', 'airport dropoff', 'meet and greet', 'flight voucher',
  'e ticket', 'electronic ticket', 'flight confirmation', 'PNR', 'booking reference', 'record locator',
  'flight miles', 'frequent flyer', 'air miles', 'loyalty points', 'rewards program',
  'domestic flight', 'international flight', 'regional flight', 'charter flight', 'private jet',
  'cargo flight', 'red eye', 'overnight flight', 'morning flight', 'afternoon flight', 'evening flight',
  'midnight flight', 'connecting airport', 'hub airport', 'regional airport', 'international airport',

  // HOTEL & ACCOMMODATION (90+)
  'hotel', 'resort', 'lodge', 'camp', 'accommodation', 'guest house', 'inn', 'motel', 'hostel',
  'bed and breakfast', 'bnb', 'airbnb', 'vacation rental', 'holiday home', 'cottage', 'cabin',
  'villa', 'apartment', 'condo', 'suite', 'room', 'standard room', 'deluxe room', 'executive room',
  'presidential suite', 'family room', 'connecting room', 'adjoining room', 'room type',
  'single room', 'double room', 'twin room', 'triple room', 'quadruple room', 'studio room',
  'one bedroom', 'two bedroom', 'three bedroom', 'hotel booking', 'room reservation',
  'check in', 'check out', 'early check in', 'late check out', 'room service', 'housekeeping',
  'breakfast included', 'half board', 'full board', 'all inclusive', 'meal plan', 'breakfast only',
  'bed and breakfast', 'room only', 'self catering', 'hotel amenities', 'pool', 'swimming pool',
  'gym', 'fitness center', 'spa', 'restaurant', 'bar', 'lounge', 'parking', 'free parking',
  'wifi', 'free wifi', 'air conditioning', 'ac', 'tv', 'television', 'minibar', 'room amenities',
  'hotel rating', 'star hotel', '5 star', '4 star', '3 star', '2 star', '1 star', 'luxury hotel',
  'boutique hotel', 'budget hotel', 'economy hotel', 'business hotel', 'airport hotel',
  'city center hotel', 'beach resort', 'beachfront', 'ocean view', 'sea view', 'mountain view',
  'garden view', 'pool view', 'hotel deals', 'hotel discounts', 'hotel packages', 'hotel offers',

  // SAFARI SPECIFIC (70+)
  'safari', 'game drive', 'morning game drive', 'afternoon game drive', 'full day game drive',
  'night game drive', 'wildlife', 'wild animals', 'big five', 'lion', 'elephant', 'rhino',
  'buffalo', 'leopard', 'cheetah', 'giraffe', 'zebra', 'hippo', 'crocodile', 'wildebeest',
  'gazelle', 'antelope', 'impala', 'hyena', 'jackal', 'fox', 'monkey', 'baboon', 'gorilla',
  'chimpanzee', 'bird watching', 'flamingo', 'ostrich', 'eagle', 'vulture', 'migration',
  'great migration', 'wildebeest migration', 'river crossing', 'mara river', 'balloon safari',
  'hot air balloon', 'walking safari', 'night safari', 'boat safari', 'canoe safari',
  'horseback safari', 'camel safari', 'photographic safari', 'honeymoon safari', 'luxury safari',
  'budget safari', 'mid range safari', 'camping safari', 'lodging safari', 'flying safari',
  'safari package', 'safari cost', 'safari price', 'safari itinerary', 'safari duration',
  'safari vehicle', 'safari guide', 'tour guide', 'ranger', 'national park', 'game reserve',
  'conservancy', 'masai mara', 'maasai mara', 'mara', 'amboseli', 'tsavo', 'tsavo east',
  'tsavo west', 'nakuru', 'lake nakuru', 'naivasha', 'lake naivasha', 'samburu', 'meru',
  'aberdares', 'mount kenya', 'ol pejeta', 'laikipia', 'rift valley', 'serengeti', 'ngorongoro',
  'tarangire', 'manyara', 'kruger', 'chobe', 'okavango', 'victoria falls', 'kidepo', 'queen elizabeth',
  'bwindi', 'volcanoes', 'akagera', 'nyungwe', 'etosha', 'sossusvlei', 'okavango delta',

  // PACKAGES & TOURS (60+)
  'package', 'tour', 'vacation package', 'holiday package', 'all inclusive package', 'fly and stay',
  'hotel and flight', 'accommodation and flight', 'honeymoon package', 'anniversary package',
  'birthday package', 'family package', 'group package', 'corporate package', 'business package',
  'student package', 'senior package', 'romantic package', 'adventure package', 'beach package',
  'mountain package', 'cultural package', 'historical package', 'religious package', 'pilgrimage',
  'city tour', 'sightseeing', 'excursion', 'day trip', 'half day tour', 'full day tour',
  'boat trip', 'boat tour', 'dhow cruise', 'sunset cruise', 'dinner cruise', 'lunch cruise',
  'snorkeling', 'diving', 'scuba', 'swimming', 'fishing', 'sport fishing', 'deep sea fishing',
  'kayaking', 'paddle boarding', 'jet ski', 'banana boat', 'parasailing', 'flyboarding',
  'bus tour', 'coach tour', 'minivan tour', 'private tour', 'group tour', 'guided tour',
  'self drive tour', 'walking tour', 'bicycle tour', 'motorcycle tour', 'quad bike tour',
  'train tour', 'luxury train', 'safari train', 'cruise', 'cruise ship', 'river cruise',
  'lake cruise', 'ferry', 'boat transfer', 'island hopping',

  // TRANSPORTATION (50+)
  'gari', 'ndege', 'bus', 'shuttle', 'shuttle bus', 'taxi', 'uber', 'bolt', 'train', 'sgr',
  'madaraka express', 'railway', 'train station', 'ferry', 'boat', 'speed boat', 'water taxi',
  'car rental', 'rent a car', 'vehicle hire', 'self drive', 'chauffeur', 'driver', 'transfer',
  'airport transfer', 'hotel transfer', 'port transfer', 'pick up', 'drop off', 'door to door',
  'tuk tuk', 'boda boda', 'motorcycle taxi', 'matatu', 'dala dala', 'tro tro', 'minibus',
  'coach', 'luxury coach', 'tour bus', 'private car', 'suv', '4x4', 'land cruiser', 'land rover',
  'toyota', 'nissan', 'subaru', 'minivan', 'hiace', 'bus rental', 'coach rental', 'group transport',
  'wedding transport', 'event transport', 'airport shuttle', 'hotel shuttle', 'park and ride',

  // PRICE & BUDGET (45+)
  'price', 'cost', 'bei', 'gharama', 'quote', 'estimate', 'budget', 'affordable', 'cheap',
  'inexpensive', 'reasonable', 'fair price', 'good price', 'best price', 'low price', 'high price',
  'expensive', 'costly', 'discount', 'deal', 'offer', 'promotion', 'sale', 'package price',
  'total cost', 'total price', 'per person', 'per night', 'per day', 'weekly rate', 'monthly rate',
  'deposit', 'down payment', 'payment', 'pay', 'installment', 'monthly payment', 'full payment',
  'balance', 'remaining balance', 'refund', 'refundable', 'non refundable', 'cancellation fee',
  'cancellation policy', 'change fee', 'rescheduling fee', 'tax', 'service charge', 'extra fee',
  'hidden fee', 'additional cost', 'optional extra', 'package includes', 'inclusions', 'exclusions',

  // DOCUMENTS & REQUIREMENTS (40+)
  'passport', 'passport copy', 'passport photo', 'passport validity', 'id', 'national id',
  'identification', 'driver license', 'driving license', 'photo', 'picture', 'application form',
  'visa form', 'travel form', 'document', 'paperwork', 'requirement', 'needed', 'required',
  'necessary', 'must have', 'need to bring', 'prepare', 'submit', 'upload', 'download',
  'scan', 'copy', 'original', 'certified copy', 'birth certificate', 'marriage certificate',
  'bank statement', 'proof of funds', 'employment letter', 'leave letter', 'invitation letter',
  'hotel voucher', 'flight itinerary', 'travel insurance', 'vaccination certificate', 'covid test',
  'pcr test', 'health form', 'customs form', 'declaration form', 'embassy form',

  // TIME & DURATION (35+)
  'today', 'tomorrow', 'day after tomorrow', 'week', 'month', 'year', 'next week', 'next month',
  'this week', 'this month', '1 day', '2 days', '3 days', '4 days', '5 days', '6 days', '7 days',
  '10 days', '14 days', '2 weeks', '3 weeks', '1 night', '2 nights', '3 nights', '4 nights',
  '5 nights', '6 nights', '7 nights', 'one day', 'two days', 'three days', 'four days', 'five days',
  'six days', 'seven days', 'overnight', 'weekend', 'weekday', 'morning', 'afternoon', 'evening',
  'night', 'midnight', 'dawn', 'dusk', 'sunrise', 'sunset', 'hour', 'minute', 'immediately',
  'asap', 'urgent', 'emergency', 'last minute', 'early booking', 'advance booking',

  // PEOPLE & GROUPS (30+)
  '1 person', '2 people', '3 people', '4 people', '5 people', '6 people', '7 people', '8 people',
  '9 people', '10 people', 'solo', 'alone', 'couple', 'married couple', 'family', 'young family',
  'large family', 'group', 'large group', 'corporate', 'business group', 'team', 'company',
  'friends', 'group of friends', 'colleagues', 'children', 'child', 'kid', 'infant', 'baby',
  'toddler', 'teenager', 'adult', 'senior', 'elderly', 'disable', 'handicap', 'single traveler',
  'female traveler', 'male traveler', 'couple traveler', 'family traveler', 'solo traveler',

  // SERVICE & SUPPORT (35+)
  'booking', 'reservation', 'confirm', 'check availability', 'is available', 'any availability',
  'service', 'help', 'assist', 'assistance', 'support', 'customer service', 'customer care',
  'help desk', 'support team', 'travel agent', 'agent', 'consultant', 'advisor', 'specialist',
  'expert', 'coordinator', 'planner', 'arranger', 'organizer', 'manager', 'guide', 'tour guide',
  'driver', 'pilot', 'host', 'hostess', 'reception', 'front desk', 'concierge', 'customer support',
  'technical support', 'emergency contact', '24/7 support', 'live chat', 'phone support',
  'email support', 'online help', 'faq', 'information', 'inquiry', 'question', 'clarification',

  // SWAHILI TRAVEL WORDS (35+)
  'safiri', 'kusafiri', 'safari', 'kwenda', 'kurudi', 'kutoka', 'kufika', 'likizo', 'mapumziko',
  'pumziko', 'nafasi', 'nafuasi', 'bei', 'gharama', 'msaada', 'nisaidie', 'saidia', 'kuwa msaada',
  'nieleze', 'nielekeze', 'nionyeshe', 'niambie', 'niachie', 'nipe', 'nataka', 'nitaka', 'tunataka',
  'wanataka', 'tunaomba', 'naomba', 'omba', 'tafadhali', 'sawa', 'poa', 'nzuri', 'fresh', 'salama',
  'habari', 'mambo', 'vipi', 'hia', 'hii', 'hizo', 'hizi', 'zile', 'zile', 'ile', 'lile', 'kile',
  'nile', 'wale', 'hawa', 'hao', 'huyu', 'yule', 'wewe', 'mimi', 'sisi', 'wote', 'pamoja', 'pekee',

  // ACTIONS & INTENTS (40+)
  'book', 'booking', 'reserve', 'reservation', 'hold', 'confirm', 'check', 'find', 'search',
  'look', 'need', 'want', 'like', 'love', 'plan', 'arrange', 'organize', 'prepare', 'make',
  'create', 'build', 'customize', 'personalize', 'nipangie', 'nipange', 'pangia', 'panga',
  'tupe', 'tupeeni', 'tuone', 'tuangalie', 'tuangalie', 'lete', 'leta', 'leteeni', 'toa',
  'patia', 'nipes', 'help me', 'help me with', 'i need', 'i want', 'i would like', 'tell me about',
  'explain to me', 'show me', 'give me', 'provide me', 'send me', 'share with me', 'let me know',
  'can i', 'can you', 'could you', 'would you', 'do you', 'is it possible', 'how to', 'how do i',
  'what is', 'what are', 'where is', 'when is', 'which one', 'which ones', 'start application',
  'lets start', 'let\'s start', 'begin', 'start', 'initiate', 'kick off', 'launch', 'proceed',
  'continue', 'move forward', 'next step', 'what next', 'what now', 'ready to book', 'ready to pay',

  // COMPLAINTS & FEEDBACK (25+)
  'sio mzuri', 'not good', 'not friendly', 'not helpful', 'not working', 'not responding',
  'hunisaidii', 'huongei', 'huzungumzi', 'hujibu', 'unajirudia', 'unanyima', 'unakasirisha',
  'asking again', 'repeat', 'again?', 'same thing', 'same message', 'annoying', 'frustrating',
  'frustrated', 'angry', 'upset', 'dissatisfied', 'bad service', 'poor service', 'terrible service',
  'worst service', 'slow response', 'no response', 'no answer', 'ignoring', 'ignored',

  // POSITIVE ACKNOWLEDGMENTS (20+)
  'hehe', 'haha', 'lol', 'lmao', 'rofl', 'ok', 'okay', 'k', 'sawa', 'sawasawa', 'poa', 'nzuri',
  'fresh', 'cool', 'nice', 'great', 'awesome', 'amazing', 'wonderful', 'fantastic', 'excellent',
  'perfect', 'superb', 'brilliant', 'lovely', 'beautiful', 'good', 'fine', 'alright', 'sounds good',
  'that works', 'perfect', 'great idea', 'love it', 'like it', 'interested', 'that\'s good',

  // FOLLOW-UP QUESTIONS (20+)
  'how much', 'how many', 'how long', 'how far', 'how soon', 'how fast', 'how early', 'how late',
  'what time', 'what day', 'what date', 'what month', 'what year', 'where at', 'where from',
  'where to', 'when exactly', 'when approximately', 'which one', 'which day', 'which month',
  'who is', 'who will', 'why is', 'why not', 'is there', 'are there', 'is it', 'are they',

  // LUXURY & BUDGET INDICATORS (15+)
  'luxury', 'deluxe', 'premium', 'vip', 'executive', 'royal', 'presidential', 'platinum', 'gold',
  'silver', 'bronze', 'standard', 'budget', 'economy', 'basic', 'simple', 'mid-range', 'mid range',
  'midrange', 'value', 'cost effective', 'high end', 'top tier', 'first class', 'business class',

  // PARK & RESERVE NAMES (30+)
  'masai mara', 'maasai mara', 'mara', 'amboseli', 'tsavo east', 'tsavo west', 'lake nakuru',
  'nakuru', 'lake naivasha', 'naivasha', 'hells gate', 'mount kenya', 'aberdare', 'samburu',
  'meru', 'shaba', 'buffalo springs', 'ol pejeta', 'sweetwaters', 'laikipia', 'kakamega',
  'malindi', 'watamu', 'arabuko sokoke', 'shimba hills', 'kisite mpunguti', 'mombasa marine',
  'diani', 'gede ruins', 'fort jesus', 'serengeti', 'ngorongoro', 'tarangire', 'manyara',
  'kilimanjaro', 'arusha', 'ruaha', 'selous', 'mikumi', 'kruger', 'pilanesberg', 'addo',

  // ACTIVITIES (25+)
  'swim', 'swimming', 'dive', 'diving', 'snorkel', 'snorkeling', 'surf', 'surfing', 'kite surf',
  'windsurf', 'paraglide', 'paragliding', 'skydive', 'skydiving', 'bungee', 'bungee jumping',
  'hike', 'hiking', 'climb', 'climbing', 'mountain climbing', 'trek', 'trekking', 'camp',
  'camping', 'fish', 'fishing', 'boat', 'boating', 'yacht', 'sail', 'sailing', 'cruise',
  'bicycle', 'cycling', 'mountain bike', 'quad bike', 'atv', 'horse ride', 'horseback riding',
  'camel ride', 'elephant ride', 'cultural tour', 'village visit', 'museum visit',

  // NUMBERS (1-10, one-ten)
  '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'one', 'two', 'three', 'four', 'five',
  'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen',
  'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty', 'thirty', 'forty', 'fifty',
  'sixty', 'seventy', 'eighty', 'ninety', 'hundred', 'thousand', 'tupige story', 'office number'
];

export const travelKeywords = travelWords;